### ISSUE TITLE
Unwanted Reboots

### ISSUE THREAD

**Issue by WWWo1f** [DCourtel/Remote_MSI_Manager#1]
I love this product but there really should be an option to not automatically reboot the remote system.  I just used it to install LibreOffice remotely on a near-by system and the user was never prompted for a reboot.  It just started closing all programs and rebooted his system.  If he had been working on a document without builtin auto-save capabilities, he could have potentially lost hours of work.
At a bare minimum, it should have at least prompted before rebooting.  Alternatively, having an option to not reboot, even if required to complete the update, would be acceptable.
As is, I can not justify using this product during business hours as it can be very disruptive which is the exact opposite reason for me using it.

**Comment by DCourtel** [comment]
Hi WWWo1f, thank you for your feedback.
Please, upgrade to release v1.0.1912.1 and let me know if the new option feat your requirement.
![image](https://user-images.githubusercontent.com/13787283/69916442-4d51b000-145b-11ea-9cce-e0323cf195ca.png)

**Comment by DCourtel** [comment]
Hi WWWo1f, please download the latest release on GitHub and test the new option:

 



 

 

Cordialement, Kind regards, 

 

David COURTEL

46, Rue de Degré - 72000 Le Mans - France

Tél : +33 9 81 45 40 11

Mobile : +33 6 01 40 88 86

-----------------------------------------------------------------------

P avant d’imprimer ce mail, pensez à l’environnement.

**Comment by WWWo1f** [comment]
I successfully installed 2 msi products (including the one that caused the reboot prior) on a test system with the new version and neither caused an unexpected reboot.  Windows Update did generate a reboot request (message popped under open windows but this is common) with a timed delay and an option to postpone.  There is still the potential for users to not notice the pop-under reboot request and suffer an unexpected reboot but that is more of a Microsoft issue.

Thank you so much for adding this feature.
